# Generated by Django 5.0.3 on 2024-05-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_productinfo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Cтатус получения заказов'),
        ),
    ]
