# Generated by Django 5.0.3 on 2024-05-14 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
